theme: minima
title: Mi CV
author: Ignacio Franco Villca Cayampi
description: Hola me presento soy programador en lenguaje Python junior me desempeño en el desarrollo backend y en analisis de datos. Manejo diferentes librerías como (Flask, Pandas, Numpy, Plotly, Seaborn, scikit-learn, openCV, Scikit-Image). Estoy en busqueda de mi primera experiencia como programador.
 
